# Generated by Django 4.2 on 2023-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTROCLIENTE', '0002_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estadp_civil',
            field=models.CharField(choices=[('SOL', 'Solteiro'), ('CAS', 'Casado'), ('DIV', 'Divorcidado'), ('VIU', 'Viuvo')], max_length=3, null=True),
        ),
    ]
