# Generated by Django 4.2 on 2023-04-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTROCLIENTE', '0003_cliente_estadp_civil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='estadp_civil',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(choices=[('SOL', 'Solteiro'), ('CAS', 'Casado'), ('DIV', 'Divorciado'), ('VIU', 'Viuvo')], max_length=3, null=True),
        ),
    ]
