# Generated by Django 4.2 on 2023-04-24 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTROCLIENTE', '0006_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Profissões'},
        ),
    ]
