# Generated by Django 4.2 on 2023-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTROCLIENTE', '0009_remove_cliente_telefone_alter_profissao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='interesses',
            field=models.ManyToManyField(to='CADASTROCLIENTE.interesses'),
        ),
    ]
