# Generated by Django 4.2 on 2023-04-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CADASTROCLIENTE', '0010_interesses_cliente_interesses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesses',
            options={'verbose_name': 'Interesse'},
        ),
    ]
